后端:
名称:git-gateway
分支机构:主

媒体文件夹:"images/uploads"
公共文件夹:/images/uploads

收藏品:
-名称:"产品"
标签:“公开产品”
文件夹:"数据/产品"
创建: true
slug:"{{sku}}"
字段:
- { 标签:“货号”, 名称:"sku"，小部件:"字符串" }
- { 标签:“产品名称”, 名称:“名称”，小部件:“字符串” }
- { 标签:“分类”, 名称:“类别”，小部件:“字符串” }
- { 标签:“图片”, 名称:“图片”，小部件:“图片” }
- { 标签:“日期”, 名称:“日期”，小部件:“日期” }

-名称:"品牌"
标签:“品牌专区”
文件夹:"数据/品牌"
创建: true
slug:"{{sku}}"
字段:
- { 标签:“货号”, 名称:"sku"，小部件:"字符串" }
- { 标签:“产品名称”, 名称:“名称”，小部件:“字符串” }
- { 标签:“图片”, 名称:“图片”，小部件:“图片” }
- { 标签:“日期”, 名称:“日期”，小部件:“日期” }
